[config]
schemaVersion = "0.0.1"

[package]
namespace = "Pegginglin"
name = "Pegginglin"
versionNumber = "0.0.3"
description = "Buttplug.io mod for Peglin"
websiteUrl = "https://github.com/qdot/pegginglin"
containsNsfwContent = true

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []